name: Victor Roman
favicon: null
layout_spectrum: 0.15340696275234222
typography_spectrum: 0.21509328484535217
title: Victor Roman Portafolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#acacac'
    - '#8a8a8a'
    - '#404040'
  brandStrength: 0.625
  lightness: 0.36959762847982347
  saturation: 0.3470285418443382
  rhythmicContrast: 0.0286289278883487
purpose: []
